version: '3.3'

services:
    frontend:
        build:
            context: .
            dockerfile: docker/Dockerfile
        tty: true
        volumes:
            - .:/app
        ports:
            - 3000:3000
            - 6006:6006
        # command: sh -c "pnpm run dev"
        # env_file:
        #   - frontend/.env.local
